apiVersion: apps/v1
kind: Deployment
metadata:
  name: dop-web
  namespace: dop
spec:
  selector:
    matchLabels:
      app: dop-web
  replicas: 1
  template:
    metadata:
      labels:
        app: dop-web
    spec:
      containers:
        - name: dop-web
          image: 172.29.7.157:85/dop/dop-web:<BUILD_TAG>
#          volumeMounts:
#            - name: host-time
#              mountPath: /etc/localtime
#            - name: host-timezone
#              mountPath: /etc/timezone
          ports:
            - containerPort: 80
#      volumes:
#        - name: host-time
#          hostPath:
#            path: /etc/localtime
#        - name: host-timezone
#          hostPath:
#            path: /etc/timezone
---
apiVersion: v1
kind: Service
metadata:
  name: dop-web
  namespace: dop
  labels:
    app: dop-web
spec:
  ports:
    - port: 14237
      protocol: TCP
      targetPort: 80
  selector:
    app: dop-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: dop-web
 namespace: dop
spec:
 rules:
   - host: www.devopsplus.com
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: dop-web
               port:
                 number: 14237
